### ISSUE TITLE
[Bug] Debug使用Hot reload时出错

### ISSUE THREAD

**Issue by llm2014** [enjkvbej/navigator_manager#3]
Flutter: 2.0.3

现象：
不做任意修改，直接在IDE中使用Hot Reload功能，出现报错：
````
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3364 pos 14: 'observer.navigator == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///.../main.dart:57:24
When the exception was thrown, this was the stack: 
#2      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:3364:14)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4632:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4469:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3303:20)
````
再次点击Hot reload, 场景恢复并重置

最小复现场景
````
var routes = {
  "/": (_, __) => CreateRoutePage(name: 'splash', child: PageSplash()),
};

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
   
    final _routerDelegate = LRouterDelegate(routes: routes);
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      routerDelegate: _routerDelegate,
      routeInformationParser: LRouteInformationParser(),
    );
  }
}

clsss PageSplash extends StatelessWidget {
  Widget build(BuildContext context) {
    return Containre();
  }
}
````

**Comment by enjkvbej** [comment]
@malody2014 hi，已升级空安全，请使用1.0.0版本。😁
